#!/bin/sh
## Note: this is the oh-my-zsh and my private-dotfiles
mkdir -p $HOME/apps

## Let's start clean shall we?
rm -rf ~/apps/oh-my-zsh

## Note: need to type the exit at the end of the process
export ZSH="$HOME/apps/oh-my-zsh"; sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"

## Clone private dotfiels (need to type username/password here)
git clone https://github.com/agilecreativity/private-dotfiles.git $HOME/apps/private-dotfiles

## Install the main dotfiles
git clone https://github.com/agilecreativity/dotfiles.git $HOME/apps/dotfiles

## TODO: move this to the optional steps e.g. 03-setup-vim-and-misc
## Then clone the rest of the dotfiles
#git clone git@github.com:agilecreativity/dotvim.git ~/apps/dotvim
#git clone git@github.com:agilecreativity/dotemacs-prelude.git ~/apps/dotemacs-prelude

## Setup fonts for use with Emacs
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/agilecreativity/sudo-make-install/master/scripts/install-source-code-pro-fonts)"
