#!/bin/sh
## Assumed that you have done the ./00-setup-oh-my-zsh script
## Setup and make sure that the ~/.ssh is up with the right credentials
mkdir -p ~/.ssh
chmod 0700 ~/.ssh
cp ~/apps/private-dotfiles/github/dot-ssh/* ~/.ssh/
cd ~/.ssh && ./setup-ssh-keys

## Then clone the rest of the dotfiles
#git clone git@github.com:agilecreativity/dotvim.git ~/apps/dotvim
#git clone git@github.com:agilecreativity/dotemacs-prelude.git ~/apps/dotemacs-prelude

## Setup fonts for use with Emacs
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/agilecreativity/sudo-make-install/master/scripts/install-source-code-pro-fonts)"
