#!/bin/bash
set -eo pipefail

## TODO: maybe check and skip if we already have ~/.rbenv locally?
rm -rf ~/.rbenv
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
mkdir -p ~/.rbenv/plugins
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
