#!/bin/bash
## TODO: maybe check and skip if we already have ~/.rbenv locally?
git clone https://github.com/rbenv/rbenv.git ~/.rbenv
git clone https://github.com/rbenv/ruby-build.git ~/.rbenv/plugins/ruby-build
