#!/usr/bin/env bash
echo "Place holder for install and setup Emacs and related config files"
## Setup fonts for use with Emacs (maybe install via Homebrew on MacOS, and package manager for Nix)
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/agilecreativity/sudo-make-install/master/scripts/install-source-code-pro-fonts)"

## Note: modify this to install dot-spacemacs instead
#git clone git@github.com:agilecreativity/dotemacs-prelude.git ~/apps/dotemacs-prelude
