#!/usr/bin/env bash
set -ex
echo "Place holder for install and setup Emacs and related config files"
## Setup fonts for use with Emacs (maybe install via Homebrew on MacOS, and package manager for Nix)
#sh -c "$(curl -fsSL https://raw.githubusercontent.com/agilecreativity/sudo-make-install/master/scripts/install-source-code-pro-fonts)"

## Note: modify this to install dot-spacemacs instead
#git clone git@github.com:agilecreativity/dotemacs-prelude.git ~/apps/dotemacs-prelude

## If we are on OSX, then use custom script to link to Emacs
platform=`uname`
if [[ $platform == 'Darwin' ]]; then
  ln -fs ~/apps/dotfiles/bin/emacs /usr/local/bin/emacs
  ln -fs /Applications/Emacs.app/Contents/MacOS/bin/emacsclient /usr/local/bin/emacsclient
fi
