#!/usr/bin/env bash
## See: https://github.com/pyenv/pyenv#basic-github-checkout
echo "rm -rf ~/.pyenv"
rm -rf ~/.pyenv
git clone https://github.com/pyenv/pyenv.git ~/.pyenv
git clone https://github.com/pyenv/pyenv-virtualenv.git ~/.pyenv/plugins/pyenv-virtualenv

## For bash use ~/.bash_profile
## Commented out as we are manually setup the ~/.zshenv via the aliases
#echo 'export PYENV_ROOT="$HOME/.pyenv"'    >> ~/.zshenv
#echo 'export PATH="$PYENV_ROOT/bin:$PATH"' >> ~/.zshenv
#echo -e 'if command -v pyenv 1>/dev/null 2>&1; then\n  eval "$(pyenv init -)"\nfi' >> ~/.zshenv
#echo 'eval "$(pyenv virtualenv-init -)"' >> ~/.zshenv
#exec "$SHELL"
#echo "You may now install python with"
#echo "pyenv install 3.5.6"  ## release date : 2018-08-02
#echo "pyenv install 2.7.15" ## release data : 2018-05-01
