# Path to your oh-my-zsh installation.
export ZSH=/Users/bchoomnuan/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
# ZSH_THEME="robbyrussell"
ZSH_THEME="avit"

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git)

# User configuration

export PATH="/Users/bchoomnuan/apps/pro-scripts/private/vha:/opt/boxen/homebrew/bin:bin:/opt/boxen/rbenv/shims:/opt/boxen/rbenv/bin:/opt/boxen/ruby-build/bin:node_modules/.bin:/opt/boxen/nodenv/shims:/opt/boxen/nodenv/bin:/opt/boxen/homebrew/bin:/opt/boxen/homebrew/sbin:/opt/boxen/bin:/opt/go/bin:/Users/bchoomnuan/go/bin:/Users/bchoomnuan/.bin:/Users/bchoomnuan/bin:/Users/bchoomnuan/apps/bin:/Users/bchoomnuan/apps/tmux-starter:/Users/bchoomnuan/apps/pro-scripts/private:/Users/bchoomnuan/apps/pro-scripts/public:/opt/boxen/homebrew/opt/android-ndk/bin:/opt/boxen/homebrew/opt/android-ndk:/opt/boxen/homebrew/opt/android-sdk/tools:/opt/boxen/homebrew/opt/android-sdk/platform-tools:/opt/boxen/homebrew/opt/android-sdk/bin:/Users/bchoomnuan/.rbenv/shims:/Users/bchoomnuan/.rbenv/bin:/Users/bchoomnuan/.rbenv:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
# export MANPATH="/usr/local/man:$MANPATH"

source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

###--------------------------------------------------------------###
### Custom config start here {{{
# Note: see the offending /etc/zsh/zshenv
# comment them out so that the $gem env work correctly inside tmux
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

## Settings for rbenv {{{
platform=`uname`
if [[ $platform == 'Linux' ]]; then
  export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv:$PATH"
  eval "$(rbenv init -)"
elif [[ $platform == 'Darwin' ]]; then
  ## Use setting from Boxen
  export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv:$PATH"
fi
## }}}

# Load common environment variable (if any)
# $ln -s ~/dotfiles/zsh/env.sh ~/.env.sh
if [ -r ~/.env.sh ]; then
  source ~/.env.sh
fi

## Load custom scripts from the a given directory {{{
## $ln -s ~/codes/bitbucket/private-dotfiles/zsh/config/ ~/.zsh.d
if [ -d ~/.zsh.d ]; then
  for i in ~/.zsh.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
## }}}
###--------------------------------------------------------------###
