# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="bira"
# Uncomment following line if you want red dots to be displayed while waiting for completion
COMPLETION_WAITING_DOTS="true"

# Plugins to be used {{{
# Plugins can be found in `~/.oh-my-zsh/plugins/*`
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(bundle \
         colorize \
         git \
         git-extra \
         gitignore \
         git-flow \
         gnu-utils \
         rake \
         rails \
         rbenv \
         sublime \
         vi-mode \
         web-search)
# }}}

source $ZSH/oh-my-zsh.sh

# Settings for rbenv {{{
export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv:$PATH"
eval "$(rbenv init -)"

# Note: see the offending /etc/zsh/zshenv
# comment them out so that the $gem env work correctly inside tmux
export PATH=/usr/local/bin:/usr/local/sbin:$PATH
# }}}

# Load common environment variable (if any)
# $ln -s ~/dotfiles/zsh/env.sh ~/.env.sh
if [ -r ~/.env.sh ]; then
  source ~/.env.sh
fi

# $ln -s ~/dotfiles/zsh/aliases.sh ~/.aliases.sh
if [ -r ~/.aliases.sh ]; then
  source ~/.aliases.sh
fi

# Load custom scripts from the a given directory {{{
# $ln -s ~/codes/bitbucket/private-dotfiles/zsh/config/ ~/.zsh.d
if [ -d ~/.zsh.d ]; then
  for i in ~/.zsh.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
# }}}
