#
ZSH=$HOME/.oh-my-zsh
#ZSH_THEME="bira"
ZSH_THEME="avit"
# Uncomment following line if you want red dots to be displayed while waiting for completion COMPLETION_WAITING_DOTS="true" # Plugins to be used {{{
# Plugins can be found in `~/.oh-my-zsh/plugins/*`
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/

#          gitignore
# )

# plugins=(bundle \
#         gitignore \
#         git-flow \
#         gnu-utils \
#         rake \
#         rails \
#         rbenv \
#         sublime \
#         vi-mode \
#         web-search)

plugins=(\
  bundle \
  colorize \
)
# }}}

source $ZSH/oh-my-zsh.sh

# Note: see the offending /etc/zsh/zshenv
# comment them out so that the $gem env work correctly inside tmux
export PATH=/usr/local/bin:/usr/local/sbin:$PATH

## Settings for rbenv {{{
platform=`uname`
if [[ $platform == 'Linux' ]]; then
  export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv:$PATH"
  eval "$(rbenv init -)"
elif [[ $platform == 'Darwin' ]]; then
  ## Use setting from Boxen
  export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv:$PATH"
fi
## }}}

# Load common environment variable (if any)
# $ln -s ~/dotfiles/zsh/env.sh ~/.env.sh
if [ -r ~/.env.sh ]; then
  source ~/.env.sh
fi

## Load custom scripts from the a given directory {{{
## $ln -s ~/codes/bitbucket/private-dotfiles/zsh/config/ ~/.zsh.d
if [ -d ~/.zsh.d ]; then
  for i in ~/.zsh.d/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
## }}}
