# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Most of the fancy themes require good fonts to look nice.
# For best result try `brew install powerline` if you are on OSX
# or `git clone git@github.com:powerline/fonts.git; cd fonts; ./install.sh`
# also https://gist.github.com/kevin-smets/8568070

# Let's be very specific about what we need to make our life easier
platform=`uname`
if [[ $platform == 'Linux' ]]; then
  ZSH_THEME="agnoster"
elif [[ $platform == 'Darwin' ]]; then
  ZSH_THEME="bira"
else
  # Use the default theme, otherwise
  ZSH_THEME="robbyrussell"
fi

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=13

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git gitignore)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

###--------------------------------------------------------------###
### Custom config start here {{{
# Note: see the offending /etc/zsh/zshenv
# comment them out so that the $gem env work correctly inside tmux

## Common to both OSX/Ubuntu
export PATH=/usr/bin:$PATH
export PATH=/usr/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

## Settings for rbenv based on the platform we are on {{{
platform=`uname`
if [[ $platform == 'Linux' ]]; then
  export PATH="$HOME/.rbenv/shims:$HOME/.rbenv/bin:$HOME/.rbenv:$PATH"
  eval "$(rbenv init -)"
elif [[ $platform == 'Darwin' ]]; then
  export PATH=$BOXEN_HOME/bin/:$PATH
  export PATH=$BOXEN_HOME/homebrew/bin:$PATH
  export PATH=$BOXEN_HOME/homebrew/sbin:$PATH
  export PATH=$BOXEN_HOME/nodenv/bin:$PATH
  export PATH=$BOXEN_HOME/nodenv/shims:$PATH
  export PATH=$BOXEN_HOME/rbenv/bin:$PATH
  export PATH=$BOXEN_HOME/rbenv/shims:$PATH
  export PATH=$BOXEN_HOME/ruby-build/bin:$PATH
fi
## }}}

## Custom Setting {{{
export PATH=$HOME/apps/dotfiles/bin:$PATH
export PATH=$HOME/apps/pro-scripts/public:$PATH
export PATH=$HOME/apps/pro-scripts/private:$PATH
# TODO: move reusable script to public!
export PATH=$HOME/apps/pro-scripts/private/vha:$PATH
export PATH=$HOME/apps/tmux-starter:$PATH
export SPIKES_HOME=$HOME/codes/spikes
## }}}

### Load public configurations {{{
if [ -d ~/apps/dotfiles/env/ ]; then
  for i in ~/apps/dotfiles/env/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
## }}}

## Load the private configurations {{{
if [ -d ~/apps/private-dotfiles/env ]; then
  for i in ~/apps/private-dotfiles/env/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi
## }}}

# For using with Android Studio on OSX
if [[ $platform == 'Darwin' ]]; then
  export ANDROID_HOME=$HOME/Library/Android/sdk
  export PATH=$ANDROID_HOME/bin:$PATH
  export PATH=$ANDROID_HOME/platform-tools:$PATH
  export PATH=$ANDROID_HOME/tools:$PATH
fi
