# Path to your oh-my-zsh installation.
export ZSH=$HOME/apps/oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.

# Most of the fancy themes require good fonts to look nice.
# For best result try `brew install powerline` if you are on OSX
# or `git clone git@github.com:powerline/fonts.git; cd fonts; ./install.sh`
# also https://gist.github.com/kevin-smets/8568070

## See: https://github.com/robbyrussell/oh-my-zsh/wiki/themes
platform=`uname`
if [[ $platform == 'Linux' ]]; then
  ZSH_THEME="agnoster"
  #ZSH_THEME="bira"
  #ZSH_THEME="bureau"
  #ZSH_THEME="robbyrussell"
  #ZSH_THEME="ys"
elif [[ $platform == 'Darwin' ]]; then
  ZSH_THEME="agnoster"
  #ZSH_THEME="bira"
  #ZSH_THEME="bureau"
  #ZSH_THEME="robbyrussell"
  #ZSH_THEME="ys"
else
  #ZSH_THEME="agnoster"
  ZSH_THEME="bira"
  #ZSH_THEME="bureau"
  #ZSH_THEME="robbyrussell"
  #ZSH_THEME="ys"
fi

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion. Case
# sensitive completion must be off. _ and - will be interchangeable.
HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to change how often to auto-update (in days).
export UPDATE_ZSH_DAYS=15

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
HIST_STAMPS="yyyy-mm-dd"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
#plugins=(common-aliases gitignore git docker docker-compose lein bundler)
plugins=(common-aliases gitignore git docker lein)

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"
source $ZSH/oh-my-zsh.sh

# You may need to manually set your language environment
export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

## -------------------------------- ##
## Custom configuration starts here ##
## -------------------------------- ##

export PATH=/usr/bin:$PATH
export PATH=/usr/sbin:$PATH
export PATH=/usr/local/bin:$PATH
export PATH=/usr/local/sbin:$PATH

platform=`uname` # for checking OS specific setting

if [[ $platform == 'Linux' ]]; then
  ## Linux specific settings
elif [[ $platform == 'Darwin' ]]; then
  ## OSX specific settings
fi

## Load public configurations
if [ -d ~/apps/dotfiles/env/ ]; then
  for i in ~/apps/dotfiles/env/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

if [ -d ~/apps/private-dotfiles/env ]; then
  for i in ~/apps/private-dotfiles/env/*.sh; do
    if [ -r $i ]; then
      . $i
    fi
  done
  unset i
fi

## ruby version manager
if [ -d ~/.rbenv ]; then
  export PATH=$HOME/.rvm/bin:$HOME/.rbenv/shims:$PATH
fi

## Make sure that /usr/local/bin comes first in the PATH
export PATH=/usr/local/bin:$PATH

if [[ $platform == 'Darwin' ]]; then
  ## OSX specific settings
  test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

  ## Use older/specific version of MySQL for Oracle's work
  if [ -f "/usr/local/opt/mysql@5.7/bin" ]; then
    export PATH=$PATH:/usr/local/opt/mysql@5.7/bin
  fi

  # ## As work around to make it possible to use older verion of Python (e.g. 3.6.x)
  # if [ -d $(pyenv root)/shims ]; then
  #   ## This allow us to use the python version from pyenv instead of the one in /usr/local/bin
  #   export PATH=$(pyenv root)/shims:$PATH
  # fi
elif [[ $platform == 'Linux' ]]; then
  ## Linux specific settings
fi
